secure:
  ignored:
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
spring:
#  激活生产环境配置
#  profiles:
#    active: dev
  servlet:
    multipart: # 上传文件配置
      max-file-size: 50MB #单个数据大小
      max-request-size: 100MB #总数据大小
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 可以解决springboot继承swagger的报错
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
#    url: jdbc:mysql://139.196.147.195:3306/acm?serverTimezone=GMT%2B8&useSSL=false&userUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/acm?serverTimezone=GMT%2B8&useSSL=false&userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.sina.com
    port: 465 # 新浪邮箱的端口
    username: comingliu@sina.com
    password: bf004cb303adce9a
    protocol: smtps
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations:
server:
  port: 8081
  ssl:
    enabled: true
    key-store: ./sslca/tomcat.keystore
    key-store-password: 12345678
    key-store-type: PKCS12
#---
#server:
#  port: 8082
#spring:
#  profiles: test
