secure:
  ignored:
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
spring:
#  激活生产环境配置
#  profiles:
#    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 可以解决springboot继承swagger的报错
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/acm?serverTimezone=GMT%2B8&useSSL=false&userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:*/*mapper.xml
server:
  port: 8080

---
server:
  port: 8081
spring:
  profiles: test