spring:
#  激活生产环境配置
#  profiles:
#    active: dev
  servlet:
    multipart: # 上传文件配置
      max-file-size: 50MB #单个数据大小
      max-request-size: 100MB #总数据大小
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 可以解决springboot继承swagger的报错
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
#      username: root
#      password: 123456
#      jdbc-url: jdbc:mysql://localhost:3306/acm?serverTimezone=GMT%2B8&useSSL=false&userUnicode=true&characterEncoding=utf-8
#      driver-class-name: com.mysql.cj.jdbc.driver
      connection-timeout: 20000 # 客户端等待连接池连接的最大毫秒数
      maximum-pool-size: 10 # 连接池最大连接数
      minimum-idle: 5 # 空闲时保持最小连接数
      connection-test-query: select 1 # 测试sql
      idle-timeout: 300000 # 空闲连接存活时间
      max-lifetime: 340000 # 连接最大存活时间
    url: jdbc:mysql://localhost:3306/acm?serverTimezone=GMT%2B8&useSSL=false&userUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  #      jdbc-url: jdbc:mysql://139.196.147.195:3306/acm?serverTimezone=GMT%2B8&useSSL=false&userUnicode=true&characterEncoding=utf-8
  mail:
    host: smtp.sina.com
    port: 465 # 新浪邮箱的端口
    username: comingliu@sina.com
    password: bf004cb303adce9a
    protocol: smtps
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:mapper
server:
  port: 8081
  ssl:
    enabled: true
#    key-store: ./sslca/tomcat.keystore
#    key-store-password: 12345678
    key-store-type: PKCS12
    key-store: classpath:7885101_dhu.ink.pfx
#    注意这里低级错误: key-password
    key-store-password: L6kcD6PR
#---
#server:
#  port: 8082
#spring:
#  profiles: test
